import { IAIService } from '@/interfaces/ai-service.interface';
import { models } from './ai.service';
import logger from '@/utils/logger';
import { retryOperation } from '@/utils/retryWithOperation';
import { ILessonGeneratorService } from '@/lib/interfaces/all-interfaces';
import { MockLessonGeneratorService } from '@/__mocks__/generated-lessons.mock';
import { GeneratedLesson, LessonStep } from '@/models/AppAllModels.model';

class LessonGeneratorService implements ILessonGeneratorService {
  private aiService: IAIService;
  private useMock: boolean;

  constructor(
    aiService: IAIService,
    useMock: boolean = process.env.NEXT_PUBLIC_MOCK_LESSON_GENERATOR === 'true'
  ) {
    this.aiService = aiService;
    this.useMock = useMock;
  }

  async generateLesson(
    topic: string,
    targetLanguage: string,
    difficultyLevel: string
  ): Promise<Record<string, unknown>> {
    try {
      if (this.useMock) {
        logger.log('Using mock lesson generator for topic:', topic);
        const mockLesson = await MockLessonGeneratorService.generateLesson(topic);
        // Wrap the mock lesson in an object with a 'data' property as an array.
        return { data: Array.isArray(mockLesson) ? mockLesson : [mockLesson] };
      } else {
        // Otherwise use the actual AI service
        const prompts = this.generateLessonPrompts(
          topic,
          targetLanguage,
          difficultyLevel
        );

        const aiResponse = await retryOperation(() =>
          this.aiService.generateContent(
            '', // No file URI needed
            prompts.userPrompt,
            prompts.systemPrompt,
            models.gemini_2_pro_exp
          )
        );

        // Make sure aiResponse is an array, then format each lesson
        const lessonsArray = Array.isArray(aiResponse) ? aiResponse : [aiResponse];
        const generatedLessons = lessonsArray.map((lesson) =>
          this.formatLessonResponse(lesson)
        );

        logger.log('Generated Lesson for topic:', topic);
        return { data: generatedLessons };
      }
    } catch (error) {
      logger.error('Error generating lesson:', error);
      throw error;
    }
  }

  private formatLessonResponse(
    aiResponse: Record<string, unknown>
  ): GeneratedLesson {
    return {
      id: '', // Populated when saved to the database.
      userId: '', // Will be assigned in the lesson service.
      lessonId: '', // To be autogenerated.
      focusArea: aiResponse.focusArea as string || 'General Conversation',
      targetSkills: aiResponse.targetSkills as string[] || ['Vocabulary', 'Grammar'],
      sequence: aiResponse.sequence as LessonStep[] || [],
      completed: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }

  private generateLessonPrompts(
    topic: string,
    targetLanguage: string,
    difficultyLevel: string
  ): { userPrompt: string; systemPrompt: string } {
    return {
      systemPrompt: `You are a helpful language tutor teaching ${targetLanguage}. 
        Create engaging lessons appropriate for ${difficultyLevel} level learners.
        Structure the lesson with a sequence of steps including prompts, new words, 
        practice opportunities, and model answers.`,
      userPrompt: `Create a comprehensive lesson about "${topic}" in ${targetLanguage} 
        for ${difficultyLevel} level students.
        Format the response as JSON with:
        - focusArea: The main focus of the lesson
        - targetSkills: Array of skills being taught
        - sequence: Array of lesson steps with:
          - step: number (sequential)
          - type: one of [prompt, new_word, practice, model_answer]
          - content: The content of the step
          - translation: English translation if applicable
        Do not include user_answer steps as these will be populated during the lesson.`,
    };
  }
}

export default LessonGeneratorService;
