export const mapLanguageToCode = (language: string): string => {
  const languageMap: Record<string, string> = {
    'german': 'de-DE',
    'english': 'en-US',
    'french': 'fr-FR',
    'spanish': 'es-ES',
    'italian': 'it-IT',
    'chinese': 'zh-CN',
    'japanese': 'ja-JP',
    'korean': 'ko-KR',
    'portuguese': 'pt-PT',
    'portuguese (brazil)': 'pt-BR',
    'russian': 'ru-RU',
    'arabic': 'ar-SA',
    'hindi': 'hi-IN',
    'bengali': 'bn-BD',
    'urdu': 'ur-PK',
    'turkish': 'tr-TR',
    'dutch': 'nl-NL',
    'swedish': 'sv-SE',
    'norwegian': 'nb-NO',
    'danish': 'da-DK',
    'finnish': 'fi-FI',
    'polish': 'pl-PL',
    'greek': 'el-GR',
    'hebrew': 'he-IL',
    'thai': 'th-TH',
    'vietnamese': 'vi-VN',
    'indonesian': 'id-ID',
    'czech': 'cs-CZ',
    'hungarian': 'hu-HU',
    'romanian': 'ro-RO',
    'slovak': 'sk-SK',
    'ukrainian': 'uk-UA',
    'croatian': 'hr-HR',
    'bulgarian': 'bg-BG',
    'serbian': 'sr-RS',
    'malay': 'ms-MY',
    'filipino': 'fil-PH',
    'persian': 'fa-IR',
    'swahili': 'sw-KE',
    'afrikaans': 'af-ZA',
    'estonian': 'et-EE',
    'latvian': 'lv-LV',
    'lithuanian': 'lt-LT',
    'slovenian': 'sl-SI',
    'catalan': 'ca-ES',
    'basque': 'eu-ES',
    'galician': 'gl-ES',
    'welsh': 'cy-GB',
    'irish': 'ga-IE',
    'scottish gaelic': 'gd-GB',
  };
  // Convert to lowercase and remove any whitespace
  const normalizedLanguage = language.toLowerCase().trim();
  
  // Return the mapped code or default to English
  return languageMap[normalizedLanguage] || 'en-US';
};